config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  post '/companies/match' => 'companies#match'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :jobs

  validates :source_id, uniqueness: true

  scope :by_source_id, ->(id) {
    where(source_id: id)
  }

  scope :with_skills, ->(skills) {
    where(%Q{
      EXISTS (
        SELECT 1
        FROM jobs_skills
        JOIN jobs ON jobs.id = jobs_skills.job_id
        WHERE jobs.company_id = companies.id AND
          jobs_skills.skill_id IN (?)
      )
    }, skills)
  }
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company

  has_and_belongs_to_many :skills

  validates :source_id, uniqueness: true

  scope :by_source_id, ->(id) {
    where(source_id: id)
  }
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, uniqueness: true

  scope :ordered, ->{ order(:name) }

  scope :more_frequent_used, -> {
    joins(%Q{
      JOIN (
        SELECT jobs_skills.skill_id, COUNT(jobs_skills.skill_id) frequency
        FROM jobs_skills
        GROUP BY jobs_skills.skill_id
      ) fr ON fr.skill_id = skills.id
      JOIN (
        SELECT AVG(frequency) media
        FROM (
          SELECT jobs_skills.skill_id, COUNT(jobs_skills.skill_id) frequency
          FROM jobs_skills
          GROUP BY jobs_skills.skill_id
        ) x
      ) media ON media.media = media.media
    }).where('fr.frequency >= media.media')
  }

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def match
    if params[:skills].blank?
      flash[:error] = 'Please, choose at least one skill'
      redirect_to root_path
    else
      @companies = Company.with_skills(params[:skills])
      @skills = Skill.find(params[:skills])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @skills = Skill.more_frequent_used.ordered
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_company.html.erb
<div class="company">
  <div class="image">
    <%= image_tag company.logo_url %>
  </div>

  <div class="details">
    <h4><%= link_to company.name, company.website_url, target: "_blank" %></h4>
  </div>
</div>

app/views/companies/match.html.erb
<h1>Check out the best companies that work with the skills you like</h1>

<p>
  Skills: <%= @skills.join(", ") %>
</p>

<% @companies.in_groups_of(4, false) do |group| %>
  <div class="row">
    <% group.each do |company| %>
      <div class="col-md-3">
        <%= render company %>
      </div>
    <% end %>
  </div>
<% end %>


<%= link_to "I want to do it again", root_path, class: "btn btn-lg btn-default" %>

app/views/home/show.html.erb
<h1>Find the best companies that work with skills you like</h1>

<h3>Choose your skills from the most used</h3>

<%= form_tag companies_match_path do %>
  <% @skills.in_groups_of(6, false).each do |group| %>
    <div class="row">
      <% group.each do |skill| %>
        <div class="col-md-2">
          <div class="form-group">
            <label>
              <%= check_box_tag "skills[]", skill.id %>
              <%= skill.name %>
            </label>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= submit_tag 'Find my dream company', class: 'btn btn-lg btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Skillboard" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>